# Generated by Django 2.2.10 on 2020-02-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racIOT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rps_id',
        ),
    ]
