# Generated by Django 2.2.10 on 2020-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racIOT', '0002_remove_user_rps_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rps_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
