# Generated by Django 2.2.10 on 2020-02-06 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racIOT', '0003_user_rps_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPS_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('year_of_birth', models.IntegerField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('last_score', models.FloatField(blank=True, null=True)),
                ('ailments', models.BooleanField(default=False)),
                ('user_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RPS_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
