# Generated by Django 2.2.10 on 2020-02-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racIOT', '0004_rps_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rps_data',
            old_name='student_id',
            new_name='entry_id',
        ),
    ]
