# Generated by Django 2.2.10 on 2020-02-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racIOT', '0005_auto_20200206_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps_data',
            name='entry_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='rps_data',
            unique_together={('user_fk', 'entry_id')},
        ),
    ]
