# Generated by Django 2.2.10 on 2020-02-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racIOT', '0006_auto_20200206_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps_data',
            name='entry_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
